apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apps.tanzu.vmware.com/workload-type: web-bp
  name: dotnet-accelerator
  namespace: default
spec:
  params:
  - name: BP_DOTNET_PROJECT_PATH
    value: src/Tanzu.WebDemo
  source:
    git:
      ref:
        branch: main
      url: https://github.com/fjb4/tap-web-demo
